name: Hexo Deploy

on:
  push:
    branches:
      - hexo

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          ref: hexo

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Setup Hexo
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "1767508581@qq.com"
          git config --global user.name "zhou-ning"
          npm install hexo-cli -g
          npm install
      - name: Set gitalk
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET}}
        run: |
          sed -i "642s/123/$CLIENT_ID/" ./themes/next/_config.yml
          sed -i "643s/123/$CLIENT_SECRET/" ./themes/next/_config.yml

      - name: Deploy
        run: |
          hexo clean
          hexo deploy
